logging:
  level:
    root: debug
    org.springframework.statemachine: off
  config: classpath:logback/logback.xml
  file:
    max-size: 100MB
    max-history: 90
    path: ./logs

spring:
  datasource:
    url: jdbc:mysql://192.168.33.10:3306/mysql?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    druid:
      async-init: true
      filters: stat,wall,slf4j
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 10000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 600000
  data:
    mongodb:
      uri: mongodb://192.168.33.10:27017/approval
  rabbitmq:
    addresses: 192.168.33.10
    password: admin
    port: 5672
    username: admin
    listener:
      direct:
        retry:
          enabled: true
          initial-interval: 2s
        prefetch: 1
      simple:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never