
spring:
  data:
    mongodb:
      uri: mongodb://192.168.33.10:27017/approval
  rabbitmq:
    addresses: 192.168.33.10
    password: admin
    port: 5672
    username: admin
    listener:
      direct:
        retry:
          enabled: true
          initial-interval: 2s
        prefetch: 1
      simple:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated